# -*- coding: utf-8 -*-
{
	"name" : "Staff Management",
	"version" : "1.10.1",
	"author" : "Luis Domingues & Romain Monnard",
	"category" : "Staff Management",
	"description" : "Management of time and task of staff.",
	"depends" : [
		'base',
		'calendar',
		'hr_timesheet',
		'account_accountant',
	],
	"init_xml" : [],
	"demo_xml" : [],
	"data" : [
		'security/staff_management_security.xml',
		'security/ir.model.access.csv',
		'views/staff_management_views.xml',
		'views/staff_tasks_accounts.xml',
		'views/staff_comment_type.xml',
		'views/staff_authorization.xml',
		'views/staff_comments.xml',
		'views/staff_events.xml',
		'views/staff_booking_type.xml',
		'views/staff_booking.xml',
		'views/staff_break_management.xml',
		'views/staff_pay_push.xml',
		'views/staff_comments_auth.xml',
		'views/staff_management.xml',
		],
	"installable" : True,
	"active" : False,
	"qweb" : ['static/*/xml/*.xml'],
}
